### PR TITLE
Default Project Styles

### PR DESCRIPTION
**Pull request by Waidhoferj**
I added some default styles to the React project so that using bare HTML tags without styled classes will get you something close to what is in the design spec. Added styles for:
- Headers h1-5
- Input fields
- paragraphs
- buttons (`wrapper` class can be used to eliminate the color styling for wrapping icons)
- Metric Badge (component)

I also added a style guide component temporarily for development. You can view all of the styles in one place at [`http://localhost:3000/style-guide`](http://localhost:3000/style-guide)

### CODE REVIEW

**Comment by gwholland3** [comment]
What would using headers or paragraphs have looked like before this?

**Comment by Waidhoferj** [comment]
@gwholland3 The default for `create-react-app` is usually the system font. For the web in general (an html file with no styles) I believe all text is Times New Roman.

**Comment by gwholland3** [comment]
So is there anything I should test other than the new style-guide route?

**Comment by Waidhoferj** [comment]
If the UI elements generally looks like the corresponding element in the design mockup, then the PR is doing its job

**Review by gwholland3 — APPROVED** [review]
Looks good

**Pull request merged**
