### PR TITLE
Added custom primary keys to Documents and Added group mutations

### PR DESCRIPTION
**Pull request by Braden50**
Added custom primary keys for the purpose of demonstration and testing. There are a couple problems with this:

- Both Artworks and Groups have a primary key related to their names/titles. 
       Currently, the creation of an artwork or group with the same name of one in the database, will cause the new object to override the id of the old one and it nulls out the old object (not deletes, it just shows up as an empty node). This makes it so a change of group or artwork name would complicate things (similar to below)
       NOTE: Artworks have a unique location attribute, but it is a special point object and I was getting errors when trying to treat it as the primary key, so I switched to title.

- Can't change user email
        Currently, If you try to change the user email then it creates a shell object with just the information provided to the update mutation. It doesn't actually update the user. Even if it did update the email, then the email would be out of sync with the id and that wouldn't be good. If it did update the id for the user then that could mess up dependencies elsewhere

Update: I added the decoding to each mutation, so now the frontend only has one type of id for each object to worry about. To my current understanding, the primary keys could be removed, and the backend would still work as expected.

### CODE REVIEW

**Review by Waidhoferj — APPROVED** [review]
Tested functionality and looked over the code. Looks great! Well done!

**Comment by gwholland3** [comment]
How can I test this?

**Comment by Waidhoferj** [comment]
@gwholland3 Heres how you test:

```
query {
  users {
    edges {
      node {
        id
      }
    }
  } 
}
```

Run that query, grab the IDs. Then shut down the server, run the same command and make sure that the IDs are the same.

**Comment by gwholland3** [comment]
When you say run, do you mean run the query on `127.0.0.1:5000/graphql`? Cuz I get an error when I run it after I turn off the server

**Comment by Braden50** [comment]
To ensure the ids formed the backend are the same between booting up you gotta run John's query on the graphql interface on 127.0.0.1:5000/graphql, note the ids, end the backend server, start the backend server again, run the same query, and then compare the ids from the two runs to make sure they're the same.

**Review by kyleshare — APPROVED** [review]
Need help testing  this, think I need to run John's query first but looks good.

**Comment by Waidhoferj** [comment]
To clarify you'll have to restart the server before running the command the second time.

**Review by gwholland3 — APPROVED** [review]
Works for me now!

**Pull request merged**
