### PR TITLE
New Account Page

### LINKED ISSUE #65: Create New Account Page
Add a form page that allows users to sign up for the app and hook it to the backend. After signing up, the user should be navigated into the app and signed in automatically.

### PR DESCRIPTION
**Pull request by gwholland3**
## Summary
Added a page for users to create a new account. It asks for a username, email, and password, all of which are required. When they user clicks Submit, they are automatically signed in and transferred to the profile page.

## Testing
Open up the app and navigate to `/new-account`. Make sure it requires all three entries to be filled before submission, and verify the user is signed in properly.

Fixes #65

### CODE REVIEW

**Review by Waidhoferj — APPROVED** [review]
LGTM. I rebased the branch and added `type="email"` to the email field.

**Comment by gwholland3** [comment]
Oh cool, does that alter the keyboard that gets pulled up on mobile?

**Comment by Waidhoferj** [comment]
I think it does. It'll also validate with a regex that ensures that the email is in the correct format.

**Review by Braden50 — APPROVED** [review]
All looks good. Looking forward to the backend implementation

**Comment by gwholland3** [comment]
> All looks good. Looking forward to the backend implementation

@Braden50 wait doesn't it already work on the backend?

**Comment by Braden50** [comment]
> > All looks good. Looking forward to the backend implementation
> 
> @Braden50 wait doesn't it already work on the backend?

Yeah my bad I must have been confused with the sign in for some reason.

**Pull request merged**
