### PR TITLE
Group Page

### PR DESCRIPTION
**Pull request by Waidhoferj**
Added a page to view group information
- Group Bio
- Group activity (simplified portfolio view)
- Metrics
- Refactored Portfolio to work with both groups and individuals
## Testing
1. Spin up backend and frontend servers.
2. Click on the Group icon (furthest to the right) in the tab bar.
3. Click on the All Artwork Welcome group
4. Verify that the bio, activity and metrics shows up
5. Click on the Portfolio icon on the Group Page in the bottom right of the header.
6. Verify that all artworks show up and the title reflects the name of the group.

### CODE REVIEW

**Comment by Waidhoferj** [comment]
Fixes #71

**Review by gwholland3 — COMMENTED** [review]
Looks good to me. 

One thing I just noticed though (not sure if it's caused by this pull request specifically) is that if I go to the comments of an artwork, I start seeing post requests made to the backend every single second. 

This continues even if I leave the comments page and go to any other page in our application, and the only way to get it to stop is by reloading the page.

**Comment by Waidhoferj** [comment]
@gwholland3 that's how the comments stay up to date between users. Apollo polls every 0.5 seconds. There's more elegant ways but this works without hitting our performance too hard. We can create an issue to investigate GraphQL subscriptions if you prefer.

**Review by kyleshare — APPROVED** [review]
Looks great.  It may make more sense for "Activity" to be "Portfolio". And a couple more metrics in the future would be cool, maybe one for "total distance traveled"

**Comment by gwholland3** [comment]
@Waidhoferj but shouldn't the polling stop once you leave the comments page? And then the next time you come back it would start polling again.

**Comment by Waidhoferj** [comment]
@gwholland3 I agree. Just made issue #90 to address it. Since this PR doesn't deal with the `Discussion` component, we should deal with it in a separate issue.

**Review by gwholland3 — APPROVED** [review]

**Review by Braden50 — APPROVED** [review]
All looks good and runs well. Good work, makes the website more fun to flow through!

**Pull request merged**
