### PR TITLE
added persistent auth

### LINKED ISSUE #75: Add OAuth to application
Research and add authorization protocol to application to remember users' credentials. Allow queries to backend.

### LINKED ISSUE #86: Persist user session
Use local storage or session cookies to store the current user in a persistent way that survives after the page is reloaded.

### LINKED ISSUE #119: Rename NewAccount to SignUp
Exactly what it sounds like

### LINKED ISSUE #127: Set Up Authentication Route Guards
When user is unauthenticated, they should only have access to:
- Sign up
- Sign in

When signed in, user should have access to all pages.

### PR DESCRIPTION
**Pull request by Waidhoferj**
Fixes #119,
Fixes #127,
Fixes #75 
Fixes #86 

Implemented [Netlify's `gotrue-js`](https://github.com/netlify/gotrue-js) authentication library for the project. 

### What it does
- Fixes our problem with persisting user after reload.
- Easy to use wrapper around oAuth
- Allows us to sign up, log in, deactivate and reactivate users.

### What it doesn't do (yet)
- Provide security for our server. We have to reach out from the server and request confirmation of a the json cookie from the Netlify service. This could get complicated, so if we're serious about it, it can be addressed in another issue.
- I haven't checked for duplicate email errors and such.

## Testing
- boot up the servers
- verify that visiting any other page but sign up and login is impossible (using url)
- go to the `/sign-up` page.
- Sign up for an account
- Verify that it takes you to the map page afterward
- Click the log out button from the user profile page
- go to the login page
- log in
- verify that you got back in

### CODE REVIEW

**Comment by Braden50** [comment]
Sign-up seems to take me to sign in. Not unexpected for an app but weird with no message. Successful login with a new account created, but it didn't redirect me to the map. I'm guessing in both of these cases the redirect takes place before authentication, so it sends me back to the login. User state and URL restrictions work great though!

**Comment by Waidhoferj** [comment]
Got it, I'll do some debugging

**Comment by gwholland3** [comment]
Noticed the same things as Braden, but also I was thinking maybe we should restrict access to `/login` and `/sign-up` when a user is logged in? I feel like it doesn't make sense for them to have access to those pages.

**Comment by Waidhoferj** [comment]
@Braden50 I couldn't reproduce, but try this fix. It might just work :)

**Review by gwholland3 — CHANGES_REQUESTED** [review]
I'm still getting a lot of buggy behavior. Some things I'm noticing are:
* Can't immediately log in as one of the four preexisting users
* Getting a "something went wrong" error when trying to sign up
* Not redirected to map screen after logging in, even though I can then manually visit `/map`

**Comment by Braden50** [comment]
> @Braden50 I couldn't reproduce, but try this fix. It might just work :)

Just tested and am getting the same results btw

**Comment by Waidhoferj** [comment]
I believe I fixed the bugs and added useful error messages. Let me know if it works for you!

**Review by Braden50 — APPROVED** [review]
It seems as though you did fix the bug I was running into good stuff! This opens the door to work on stuff like logout, and editing the user profile which I can make as issues if we have the time. 

Let me also note that my PR added the join group mutation and it looks like that is in your next issue, so let me know if you move onto it before getting my PR through.

**Review by gwholland3 — CHANGES_REQUESTED** [review]
Still getting almost all of the same behavior as before...

Except one thing that's changed is instead of getting a "something went wrong" error when I try to sign up a new user, I get "a user with this email address has already been registered"

**Comment by Waidhoferj** [comment]
@gwholland3 Did you register with the same email?

**Comment by gwholland3** [comment]
@Waidhoferj No I tried it with multiple new emails

**Comment by Waidhoferj** [comment]
Okay I think we're gonna have to tackle this as a group.

**Review by gwholland3 — APPROVED** [review]
Looks good

**Review by kyleshare — APPROVED** [review]
Works good!

**Pull request merged**
