### PR TITLE
Braden50/report content page

### LINKED ISSUE #73: Report Content Page
Create a page that allows users to report an artwork as inappropriate.
Should have:
- Description
- A dropdown category: duplicate, inappropriate, not art.
- Submit button

### PR DESCRIPTION
**Pull request by Braden50**
Added the report page on the frontend and its functionality in the back

There were also a couple of edits I made to fix up other mutations (ex: Group and artwork)
Adding testing to make sure we aren't missing anything when a report is submitted

NOTE: Frontend feels weird without a "you submitted a report!" kind of response. I wasn't sure how to do this exactly in due time. 

To test:

1. Boot up the frontend and backend ("python app.py -l")
2. Go to the map
3. Look at an already discovered artwork
4. "View in my portfolio"
5. Click the report button
6. Fill out and submit the form
7. Run the query below on the backend (http://localhost:5000/graphql) to make sure your report is now in the database
     - NOTE: You can use reports(last: 1) { ... } to see the most recent report.

{ 
  reports {
    edges {
      node {
        reportedIdType
        reportedId
        userId
        reason
        description
        dateSubmitted
      }
    }
  }
}

### CODE REVIEW

**Review by kyleshare — COMMENTED** [review]
I'm getting a "TypeError, cannot read property 'node' of undefined" when I run it. It looks like it's from the useProfileInfo hook. Also I can't see any artworks on the art map now. Anyone else getting this issue?

**Comment by Braden50** [comment]
Sorry, I forgot to specify to run the backend with the "-l" flag. I'm guessing that bug is coming from running the cloud db because the schema has been changed quite a bit since data was last pulled from it.

**Review by kyleshare — APPROVED** [review]
Looks great! Just a thought, anything that falls under the "Inappropriate" category probably also falls under the "Not Art" category. So combining them may be something to consider.

**Review by Waidhoferj — APPROVED** [review]
Works really well! The code looks great too!

**Review by gwholland3 — APPROVED** [review]
Looks good, nice job!

**Pull request merged**
