### PR TITLE
GraphQL Integration between frontend and backend

### LINKED ISSUE #22: Map Screen: Fetch actual art data
Be able to get art locations from the database and display at least the title, description, and location on the frontend

Additional attributes of the location like pictures and comments can be saved for another issue

### LINKED ISSUE #29: Add support for local development server
We have a mongo mock server in the `Research` folder. It would be nice to be able to use the mock server in development and cloud server for production. We could use a conditional flag when the backend starts up to determine which server to use. For example `python app.py -d` to user the development server.
- Add mongo mock to the `backend` project
- Parse `-d` arg from the command line
- Conditionally choose server based on presence of `-d`
- Ensure both server types work with new setup

### LINKED ISSUE #36: Setup GraphQL frontend library
We need a library to make GraphQL querying easier on the React frontend. Keep in mind that we are using a Graphene implementation in the backend, so the library cannot be opinionated about backend libraries.

Deliverables:
- Get the library working with an example query
- Show group members how to use it

### PR DESCRIPTION
**Pull request by Waidhoferj**
The frontend can now pull data from the backend.

## Changelog:
- Added option to launch a local server instead of using the cloud instance by calling `python app.py -l`
- Dynamically imports `secrets.py`. If user doesn't have it, launches the mock instance instead of erroring.
- Made some updates to the mock server.
- Added CORS to the flask server so that the frontend can access the api
- Added Apollo Client to the frontend in order to cache fetches from graphql api.
- Integrated the map with the graphql api. Data is now pulled directly from the server launched in the backend folder.
## Testing:
1. Launch the backend server in `/backend`: `pipenv install && pipenv shell && python app.py -l`
2. Launch the website in `/frontend`: `npm install && npm start`
3. Go to `/map` page.
4. Ensure that you can interact with the artworks. The data for these artworks can be found in `database.py`
## Resources:
[Apollo Client](https://www.apollographql.com/docs/react/)

Fixes #22, fixes #29, fixes #36

### CODE REVIEW

**Comment by gwholland3** [comment]
I need to run `pipenv install` before the `python app.py -l` right?

**Review by kyleshare — APPROVED** [review]
I definitely completely understand what's going on here!

**Comment by Waidhoferj** [comment]
@gwholland3 yeah this assumes you've done the basic repo setup. It's a good idea to run pipenv install again since I added flask-cors

**Comment by gwholland3** [comment]
For me, the frontend fails to compile. I get this error:
```
./src/App.js
Module not found: Can't resolve '@apollo/client' in '/Users/grantholland/Grant/Cal Poly/2020-2021/Winter Quarter/CSC 308-01/CSC-308-309-Project/frontend/src'
```

**Comment by Waidhoferj** [comment]
@gwholland3 Npm install first

**Review by Braden50 — APPROVED** [review]
All looks and runs great! Thanks for working out the integration John. I am going to likely override your mock data in database.py with mutations after you merge. I had hoped to merge my mock data earlier, but I wanted to test and confirm each mutation first.

**Pull request merged**
