### PR TITLE
Art review

### PR DESCRIPTION
**Pull request by kyleshare**
Create Art Review page, also add validation to ensure rating is required for ArtReview and ArtSubmission pages.

### CODE REVIEW

**Comment by Waidhoferj** [comment]
Screen Shot 2021-04-15 at 5 47 04 PM
@kyleshare When I click on the review button, it doesn't go to the review page.

**Comment by gwholland3** [comment]
When I try to run `npm install` before starting the app, I get this error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: frontend@0.1.0
npm ERR! Found: mapbox-gl@2.2.0
npm ERR! node_modules/mapbox-gl
npm ERR!   mapbox-gl@"^2.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer mapbox-gl@"^1.12.0" from react-mapbox-gl@5.1.1
npm ERR! node_modules/react-mapbox-gl
npm ERR!   react-mapbox-gl@"^5.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/grantholland/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/grantholland/.npm/_logs/2021-04-16T22_11_02_411Z-debug.log
```

**Comment by kyleshare** [comment]
Should be working now.

**Comment by gwholland3** [comment]
I still get the same error when I run `npm install`...

**Comment by Waidhoferj** [comment]
@kyleshare thanks for fixing the button! I'm able to launch the branch for review, but when I submit the form I'm getting this error. Could you fix this?
Screen Shot 2021-04-20 at 4 10 12 PM

**Comment by Waidhoferj** [comment]
Its probably something with the way you are passing the data to Apollo.

**Pull request merged**
