### PR TITLE
Art Submission

### PR DESCRIPTION
**Pull request by Waidhoferj**
You can now submit new artwork to our app!

## Updates
- The `CreateArtworkMutation` now accepts a `pictures` attribute that is an array of images.
- The `CreateArtworkMutation` uses `foundBy` to add the artwork to the user's `personalPortfolio`
- From the camera page, users can't press the "go to art submission arrow" button on the right until they have taken one picture.
- Added styles to the ArtworkSubmission page
- Added logic to submit the artwork using `CreateArtworkMutation` 
- Handled navigation to the Artwork screen after user submits the form

## Known issues
- The screen doesn't play so nice with the TabBar component. Scrolling is a bit funky.
- No error handling for the mutation logic

Despite this, I think we should push forward and correct any issues after the demo (next quarter)

## Testing
1. Boot up frontend and backend servers
2. Go to the camera page.
2. Take a photo
3. Press the right arrow button onscreen on the camera page.
4. Fill out all of the fields on the Art Submission page
5. Press Post Art
6. Verify that you see an art page populated with the information that you submitted.

### CODE REVIEW

**Comment by Waidhoferj** [comment]
Fixes #32, fixes #24, fixes #17

**Comment by Braden50** [comment]
Looks like the rating conversion might be off. The ratings show up as 0.2, 0.25, and 0.05  when I input stars of (I think) 1, 3, and 5. I believe the backend is expecting a float value from 1 to 100. Navbar issues are there like you said and that seems fine to commit for demonstration. I also seem to have to manually refresh my map screen for the added artworks to show up instead of using the navbar to get to the map. Even if I refresh my portfolio page, the new artworks don't show up in my portfolio. It looks like that functionality was added to the backend, but I don't know if I'm expected to test it as well. I'm not sure where the error for that would be. All else about the page looks great!  

I can submit my approval despite these notes though because we need this PR for demonstration.

**Review by Braden50 — APPROVED** [review]
Approved! (See comment)

**Comment by gwholland3** [comment]
Yeah noticing the same issues as Braden, and additionally it looks like after you submit an artwork, the photos you took aren't cleared from the camera library.

**Review by gwholland3 — APPROVED** [review]
It looks nice though!

**Comment by Waidhoferj** [comment]
Made requested changes

**Pull request merged**
