### PR TITLE
Braden50/environmental-vars

### PR DESCRIPTION
**Pull request by Braden50**
Solved issue #93

To test:

Either set the environmental variables on your computer (within the virtual environment or not I'm not sure) or you can just put the .env file I gave you all into the backend folder. In the latter case, pipenv will read the file and create the environmental variables.

Technically you can test this by just making sure the backend boots up correctly with both tag combos: "-l" "-l --testing", but this merge will technically be tested everytime a new push is made since it runs the tests.

### CODE REVIEW

**Comment by gwholland3** [comment]
Ok, so I checked out your branch, added the `.env` file to `backend/`, and removed `secrets.py`. Then I ran `pipenv install` and `pipenv shell` followed by `python app.py -l`.

I get the tip: `There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.`
However, when I boot up the frontend, it looks like everything runs fine. Is all of this expected?

**Comment by gwholland3** [comment]
Oh also my `yarn.lock` gets modified, is that also ok?

**Comment by Braden50** [comment]
Yeah the tip suggests using a module that instantly imports all the environmental variables as python variables. Not needed right now for our implementation in my opinion.

I rebased with main to be safe, and it seems to have stacked some commits from John or Kyle onto this PR which I am confused by

**Review by Waidhoferj — APPROVED** [review]
LGTM

**Review by gwholland3 — APPROVED** [review]
Fingers crossed lol

**Pull request merged**
