### PR TITLE
Map Overlays

### LINKED ISSUE #4: Simple Map Screen
- Show that we can load a map of the world
- Position of user in world
- Draw locations of key areas from [longitude, latitude] pairs

Highly recommend using [react-mapbox-gl](https://github.com/alex3165/react-mapbox-gl)

### PR DESCRIPTION
**Pull request by gwholland3**
Added a JSON file to store locations of the user/artworks as points. 

Added a GeoJSONLayer to the Map to display these locations as colored circles, with different colors for user position and artworks.

Added a reference to an empty `handleClick` function in `ArtMap.jsx` that is called when any circle is clicked on.

### CODE REVIEW

**Comment by gwholland3** [comment]
Fixes #4

**Review by Waidhoferj — APPROVED** [review]
Looks great! I love how you're dynamically fetching the color!

**Review by Braden50 — APPROVED** [review]
Looks good visually

**Review by kyleshare — APPROVED** [review]
Looks great!

**Comment by Waidhoferj** [comment]
@gwholland3 send it dude 👏

**Pull request merged**
