### PR TITLE
App Navigation

### PR DESCRIPTION
**Pull request by Waidhoferj**
Added Tab Bar to the bottom left of the screen on large/medium, which folds into a mobile style tab bar on small along the bottom of the app.

Test to see if it blocks anything in an egregious way on large/medium. I tested it on map, artwork and camera screens.

### CODE REVIEW

**Comment by Waidhoferj** [comment]
Fixes #48

**Review by gwholland3 — COMMENTED** [review]
It looks really nice! All the functionality works for me, and I like the change from left tab bar to full screen.

**Comment by gwholland3** [comment]
The one issue I did find is this:

Screen Shot 2021-03-13 at 16 15 42

There is a little bit of overlap with the tab bar and the photo library button on the camera page if I resize my window a certain way.

**Comment by Waidhoferj** [comment]
Oh good catch, I'll make a few adjustments

**Review by Braden50 — APPROVED** [review]
Very good and useful. Nice work.

**Pull request merged**
