### PR TITLE
Braden50/applying style and adding errors

### PR DESCRIPTION
**Pull request by Braden50**
References #61 and #116

Got pycodestyle to pass for to all files in the backend
Created mutations.txt to store sample mutations instead of putting them at the bottom of mutations.py
Added docstrings to mutations and some api_types
Refactored some mutations to restrict changes we don't want
Added comments for future mutation refactoring

To test:

Did not really edit any functionality other than removing capabilities from mutations that we aren't using anyway. You could boot it up just to make sure it all works. Feel free to check out the mutation and type descriptions in the grapqhl interface if you're curious or want to critique my grammar. I wouldn't be hurt.

### CODE REVIEW

**Review by gwholland3 — CHANGES_REQUESTED** [review]
The docstrings look good and the Python is clean!

There do seem to be some merge conflicts after all those other PRs went through though, so you should probably rebase.

**Comment by gwholland3** [comment]
Maybe I'm doing something wrong, but now I'm getting pycodestyle warnings on mutations.py?

**Review by gwholland3 — APPROVED** [review]
👍

**Review by Waidhoferj — APPROVED** [review]
Great work! The code looks so much cleaner! 👍

**Review by kyleshare — APPROVED** [review]
Looks really good!

**Pull request merged**
