### PR TITLE
iPhone bug fixes

### LINKED ISSUE #104: Fix Buttons on iPhone
Make sure iPhone doesn't override our styling for buttons

### PR DESCRIPTION
**Pull request by Waidhoferj**
Fixes: #104 

## Changes
- Fixed submit button appearance on safari
- Reduced height of artwork headers so that it is easier to view on phones
- Sized app screen correctly so that UI of browser doesn't cover up our tab bar
- Disabled overflow scroll bounce for the top level app container

### CODE REVIEW

**Review by gwholland3 — CHANGES_REQUESTED** [review]
I'm still getting the tab bar covered up on my iPhone...
D43E26F1-55DD-41C0-B3A7-1E410EBA791D

**Comment by Waidhoferj** [comment]
@gwholland3 That's not the branch for this PR, that is the live site.

**Review by kyleshare — COMMENTED** [review]
This is pretty awesome.

A few things, I was able to submit new artworks fine but when I reviewing an existing artwork I couldn't get the rating to update, also the icons are shifting around a bit.
IMG_1722


Also whenever I tried to access the comments for an artwork I got a blank screen.
IMG_1720

Lastly I was getting this message when trying to view my group, but after closing the app and refreshing a few times I was able to view it.
IMG_1723

**Comment by kyleshare** [comment]
> I'm still getting the tab bar covered up on my iPhone...
> D43E26F1-55DD-41C0-B3A7-1E410EBA791D

I believe you just have to drag up on the bottom left around where it says mapbox to fix this

**Comment by kyleshare** [comment]
@gwholland3 I believe this is fixed by dragging up from the bottom of the screen, around where it says mapbox

**Comment by Waidhoferj** [comment]
@kyleshare @gwholland3 You cannot use your iPhones to test this. The website you are visiting is the main branch. None of the changes that I made on this branch are deployed to main. To test on iOS Safari you would have to run an emulator from Xcode and go to localhost:3000

**Review by Braden50 — APPROVED** [review]
Seems like I would have to jump through a lot of hoops to test this completely (being on windows). Right now I can trust your styling and approve the PR (plus you showed us yesterday visually). I'll try to do a "test" of these edits on the deployed version once the PR goes through.

**Comment by gwholland3** [comment]
Whoops my b 🤦

**Comment by gwholland3** [comment]
Can you simulate that on chrome?

**Comment by Waidhoferj** [comment]
You can simulate the size in dev tools, but the bugs won't show up because it's using the desktop browser engine. To really test it, you'd need to boot up the emulator. But as long as nothing breaks on desktop we should be good to go

**Review by gwholland3 — APPROVED** [review]
Ok, I'll take your word for it

**Pull request merged**
