### PR TITLE
Small Fixes

### LINKED ISSUE #100: Rename Submit Button on Art Review Page from "Post Art" to "Post Review"
Nuff' said

### PR DESCRIPTION
**Pull request by gwholland3**
## Summary
* Renamed the submit button on ArtReview from "Post Art" to "Post Review"
* Added an error message on ArtReview if the user does not give a rating
* Renamed the NewAccount page to SignUp
* Resolved a package vulnerability

## Testing
New URL for the sign-up page is `/sign-up`, make sure it works. 
Verify that you get 0 vulnerabilities when you run `npm install`. 
Go to any artwork and submit a review, make sure the submit button is appropriately named and that an error message lets you know when you didn't give a rating.

Fixes #100

### CODE REVIEW

**Comment by Braden50** [comment]
The sign-up seems to be working except it still doesn't change the user state, not sure if that was fixed before this or not. 
The art review form all looks and works well
I ran 'npm install' and 'npm audit fix' a few times and still get the errors below. It looks like these are my personal errors though because "fsevent" seems to not expect windows os, and it suggests I fix the mapbox issues myself. Since this seems to be the case (and our app will probably not be deployed on windows?) I'll approve the PR.

`npm WARN react-mapbox-gl@5.1.1 requires a peer of react@^16.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-mapbox-gl@5.1.1 requires a peer of react-dom@^16.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 1859 packages in 13.204s

127 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability`

**Review by Braden50 — APPROVED** [review]

**Comment by gwholland3** [comment]
Yeah the sign-in bug is a separate issue.

So you're getting those warning messages now when you run `npm install`?

**Comment by Braden50** [comment]
> Yeah the sign-in bug is a separate issue.
> 
> So you're getting those warning messages now when you run `npm install`?

Yeah, I believe so. I could look into the packages, but I'm not sure if it's necessary.

**Review by Waidhoferj — APPROVED** [review]
Looks good!

**Review by Waidhoferj — APPROVED** [review]
LGTM

**Review by Braden50 — APPROVED** [review]
All looks good, NICE

**Pull request merged**
